### ISSUE TITLE
思考stall unit的实现

### ISSUE THREAD

**Issue by maoyuchaxue** [char-fish-after-lunch/cat-pad#2]
1.  确定它需要处理哪些冲突，以及需要哪些信号来判定冲突，并且对于这些冲突分别进行何种操作
2.  实现stall unit
3.  为其他各部分添加相应接口

**Comment by jasonyu1996** [comment]
Support for RAW conflict resolving and branch added. Fibonacci is tested.

Next step: design new test samples.

**Comment by jasonyu1996** [comment]
Tested on a modified Fibonacci. The delay slot now works properly. 

Next step: resolve structural conflicts.

**Comment by jasonyu1996** [comment]
Done. Structural conflicts and RAW conflict between IF and MEM resolved.

Next step: test these functions after RAM becomes available.

**Comment by jasonyu1996** [comment]
Done. More tests will be carried out in the future.
